# Generated by Django 4.1.7 on 2023-04-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('company_name', models.CharField(max_length=255)),
                ('job_location', models.CharField(max_length=255)),
            ],
        ),
    ]
